# SPDX-FileCopyrightText: 2020 Tuomas Siipola
# SPDX-License-Identifier: CC0-1.0

name: Test

on: [push, pull_request]

jobs:
  reuse:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: REUSE Compliance Check
      uses: fsfe/reuse-action@v1.1

  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        compiler: ['gcc', 'clang']
    env:
      CC: ${{ matrix.compiler }}
    steps:
      - uses: actions/checkout@v2
      - run: make
      - run: make test
